insert into users_details(id, date_ofbirth,name) values(101, current_date(),'Khan')
insert into users_details(id, date_ofbirth,name) values(102, current_date(),'Imran')
insert into users_details(id, date_ofbirth,name) values(103, current_date(),'Ahmad')
insert into users_details(id, date_ofbirth,name) values(104, current_date(),'Jawad')
insert into users_details(id, date_ofbirth,name) values(105, current_date(),'Jhon')

insert into post(id,description,user_id) values(1,'I wan to learn Spirng boot',101)
insert into post(id,description,user_id) values(2,'I wan to learn Spirng ',101)
insert into post(id,description,user_id) values(3,'I wan to learn react',101)
insert into post(id,description,user_id) values(4,'I wan to learn javascript',101)

insert into post(id,description,user_id) values(5,'learn java',102)
insert into post(id,description,user_id) values(6,'learn spring ',102)
insert into post(id,description,user_id) values(7,'learn spring',102)
insert into post(id,description,user_id) values(8,'learn jav',101)